apiVersion: v1
kind: Service
metadata:
  name: {{ include "janusgraph-cluster.fullname" . }}
  labels:
    {{- include "janusgraph-cluster.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: websocket
      protocol: TCP
      name: websocket
  selector:
    {{- include "janusgraph-cluster.selectorLabels" . | nindent 4 }}
